
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"

  
  config.vm.provision "shell",
    inline: <<FINE 
      echo "Update package list"
    	sudo apt-get update
      
      echo "Install docker"
      sudo wget -qO- https://get.docker.com/ > docker_install
      sudo chmod u+x docker_install
      sudo ./docker_install
      sleep 5
    	sudo usermod -a -G docker vagrant

      sudo docker login
FINE
  
  config.vm.synced_folder "../dockers", "/docker_build"
  
  config.vm.define "vmb" do |vmb|
    vmb.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

end
