
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"

  
  config.vm.provision "shell",
    inline: <<FINE 
      echo "Update package list"
    	sudo apt-get update
      
      # - install software needed to build zeppelin
      apt-get install -y -q nodejs npm libfontconfig git wget
      
      cd /usr/bin/ && ln -s nodejs node \
      && npm install -g bower \
      && npm install -g grunt
      
      #     install maven
      wget http://www.eu.apache.org/dist/maven/maven-3/3.3.3/binaries/apache-maven-3.3.3-bin.tar.gz \
      && tar -zxf apache-maven-3.3.3-bin.tar.gz -C /usr/local/ \
      && ln -s /usr/local/apache-maven-3.3.3/bin/mvn /usr/local/bin/mvn

      echo "Install docker"
      sudo wget -qO- https://get.docker.com/ > docker_install
      sudo chmod u+x docker_install
      sudo ./docker_install
      sleep 5
    	sudo usermod -a -G docker vagrant

      sudo docker login
FINE
  
  config.vm.synced_folder "../tudelft_lab", "/docker_build"
  
  config.vm.define "vmb" do |vmb|
    vmb.vm.provider "virtualbox" do |v|
      v.memory = 4096
      v.cpus = 2
    end
  end

end
