
Vagrant.configure("2") do |config|
  
  config.vm.box = "ubuntu/trusty64"

  
  config.vm.provision "shell",
    inline: <<FINE 
      echo "Update package list"
    	sudo apt-get update
      sleep 5

      echo "Install package for VPN"
      sudo apt-get install -qy openvpn iptables socat curl openssh-server

      echo "Install docker"
      sudo wget -qO- https://get.docker.com/ > docker_install
      sudo chmod u+x docker_install
      sudo ./docker_install
      sleep 5
    	sudo usermod -a -G docker vagrant

      echo "Install weave net"
      wget git.io/weave
      chmod a+x weave

      echo "Install weave scope"
      wget https://github.com/weaveworks/scope/releases/download/latest_release/scope
      chmod a+x scope

      echo "Setup user env"
      echo "" >> .bashrc 
      echo "" >> .bashrc 
      echo "eval \\$( ./weave env )" >> .bashrc 

FINE
  
  config.vm.define "vm1" do |vm1|
    vm1.vm.network "private_network", ip: "192.168.33.11"
    vm1.vm.hostname = "vm1"

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 1
    end
  end

  config.vm.define "vm2" do |vm2|
    vm2.vm.network "private_network", ip: "192.168.33.12"
    vm2.vm.hostname = "vm2"

    config.vm.provider "virtualbox" do |v|
      v.memory = 2048
      v.cpus = 2
    end
  end
end
